export enum languages {
  Arabic = "ar",
  Chinese = "zh",
  Danish = "da",
  German = "de",
  English = "en",
  Finnish = "fi",
  French = "fr",
  Hebrew = "he",
  Indonesian = "id",
  Italian = "it",
  Japanese = "ja",
  Korean = "ko",
  Dutch = "nl",
  Polish = "pl",
  Portuguese = "pt",
  Russian = "ru",
  Swedish = "sv",
  Spanish = "es",
  trad_Chinese = "zh-TW",
  Czech = "cs",
  Turkish = "tr",
}
